# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CBE Jamf Guide
tagline: A guide for the CBE Jamf 
description: A guide for the CBE Jamf 
author: Yiyang (Ian) Wang
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://cbe-computing.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.0
color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Just the Class on GitHub:
    - 'https://github.com/kevinlin1/just-the-class'

back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2024 Yiyang (Ian) Wang. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/CBE-Computing/CBE-Computing.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Collections for website data
collections:
  authors:
  modules:
  schedules:
  announcements:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

# callouts
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important Announcement
    color: red
  note:
    title: Note
    color: yellow
  success:
    title: ""
    color: green